/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    bolEchoDouble
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_HelloJNI_bolEchoDouble
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     HelloJNI
 * Method:    intEchoDouble
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_intEchoDouble
  (JNIEnv *, jclass, jint);

/*
 * Class:     HelloJNI
 * Method:    strEchoDouble
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_strEchoDouble
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
